/* This file was automatically generated.  Do not edit! */
void quicktime_atom_write_footer(quicktime_t *file,quicktime_atom_t *atom);
void quicktime_write_pascal(quicktime_t *file,char *data);
int quicktime_write_int32(quicktime_t *file,long value);
int quicktime_write_char32(quicktime_t *file,char *string);
int quicktime_write_int24(quicktime_t *file,long number);
int quicktime_write_char(quicktime_t *file,char x);
int quicktime_atom_write_header(quicktime_t *file,quicktime_atom_t *atom,char *text);
void quicktime_write_hdlr(quicktime_t *file,quicktime_hdlr_t *hdlr);
void quicktime_read_pascal(quicktime_t *file,char *data);
long quicktime_read_int32(quicktime_t *file);
void quicktime_read_char32(quicktime_t *file,char *string);
long quicktime_read_int24(quicktime_t *file);
int quicktime_read_char(quicktime_t *file);
void quicktime_read_hdlr(quicktime_t *file,quicktime_hdlr_t *hdlr);
void quicktime_hdlr_dump(quicktime_hdlr_t *hdlr);
void quicktime_hdlr_delete(quicktime_hdlr_t *hdlr);
void quicktime_hdlr_init_data(quicktime_hdlr_t *hdlr);
void quicktime_hdlr_init_audio(quicktime_hdlr_t *hdlr);
void quicktime_hdlr_init_video(quicktime_hdlr_t *hdlr);
void quicktime_hdlr_init(quicktime_hdlr_t *hdlr);
