/* This file was automatically generated.  Do not edit! */
int quicktime_register_external_acodec(const char *codec_name);
int quicktime_register_external_acodec(const char *codec_name);
int quicktime_register_external_vcodec(const char *codec_name);
int quicktime_register_external_vcodec(const char *codec_name);
void quicktime_register_internal_vcodec();
void quicktime_register_internal_vcodec();
void quicktime_register_internal_acodec();
void quicktime_register_internal_acodec();
int quicktime_register_acodec(char *fourcc,void(*init_acodec)(quicktime_audio_map_t *));
int quicktime_register_acodec(char *fourcc,void(*init_acodec)(quicktime_audio_map_t *));
void quicktime_copy_char32(char *output,char *input);
int quicktime_register_vcodec(char *fourcc,void(*init_vcodec)(quicktime_video_map_t *));
int quicktime_register_vcodec(char *fourcc,void(*init_vcodec)(quicktime_video_map_t *));
int quicktime_acodec_size();
int quicktime_acodec_size();
int quicktime_vcodec_size();
int quicktime_vcodec_size();
int quicktime_update_tables(quicktime_t *file,quicktime_trak_t *trak,longest offset,longest chunk,longest sample,longest samples,longest sample_size);
int quicktime_write_data(quicktime_t *file,char *data,int size);
longest quicktime_position(quicktime_t *file);
int quicktime_read_data(quicktime_t *file,char *data,longest size);
long quicktime_frame_size(quicktime_t *file,long frame,int track);
long quicktime_frame_size(quicktime_t *file,long frame,int track);
int quicktime_set_video_position(quicktime_t *file,longest frame,int track);
int quicktime_set_video_position(quicktime_t *file,longest frame,int track);
char *quicktime_video_compressor(quicktime_t *file,int track);
char *quicktime_video_compressor(quicktime_t *file,int track);
int quicktime_find_acodec(char *fourcc);
int quicktime_find_acodec(char *fourcc);
int quicktime_match_32(char *input,char *output);
int quicktime_find_vcodec(char *fourcc);
int quicktime_find_vcodec(char *fourcc);
