int quicktime_init(quicktime_t *file);
int quicktime_atom_read_header(quicktime_t *file, quicktime_atom_t *atom);
int quicktime_atom_is(quicktime_atom_t *atom, char *type);
int quicktime_atom_skip(quicktime_t *file, quicktime_atom_t *atom);
int quicktime_shift_offsets(quicktime_moov_t *moov, longest offset);
void quicktime_write_moov(quicktime_t *file, quicktime_moov_t *moov);
int quicktime_set_udta_string(char **string, int *size, char *new_string);
int quicktime_match_32(char *input, char *output);
int quicktime_trak_init(quicktime_trak_t *trak);
int quicktime_moov_init(quicktime_moov_t *moov);
int quicktime_delete_audio_map(quicktime_audio_map_t *atrack);
int quicktime_delete_video_map(quicktime_video_map_t *vtrack);
int quicktime_trak_init(quicktime_trak_t *trak);
int quicktime_moov_init(quicktime_moov_t *moov);
int quicktime_delete_audio_map(quicktime_audio_map_t *atrack);
int quicktime_moov_delete(quicktime_moov_t *moov);
void quicktime_mdat_delete(quicktime_mdat_t *mdat);
int quicktime_delete_vcodec(quicktime_video_map_t *vtrack);
int quicktime_delete_acodec(quicktime_audio_map_t *atrack);
void quicktime_read_char32(quicktime_t *file, char *string);
void quicktime_read_mdat(quicktime_t *file, quicktime_mdat_t *mdat, quicktime_atom_t *parent_atom);
int quicktime_read_moov(quicktime_t *file, quicktime_moov_t *moov, quicktime_atom_t *parent_atom);
void quicktime_moov_dump(quicktime_moov_t *moov);
int quicktime_codecs_flush(quicktime_t *file);
void quicktime_atom_write_footer(quicktime_t *file, quicktime_atom_t *atom);

