/* This file was automatically generated.  Do not edit! */
void quicktime_atom_write_footer(quicktime_t *file,quicktime_atom_t *atom);
void quicktime_write_minf(quicktime_t *file,quicktime_minf_t *minf);
void quicktime_write_hdlr(quicktime_t *file,quicktime_hdlr_t *hdlr);
void quicktime_write_mdhd(quicktime_t *file,quicktime_mdhd_t *mdhd);
int quicktime_atom_write_header(quicktime_t *file,quicktime_atom_t *atom,char *text);
void quicktime_write_mdia(quicktime_t *file,quicktime_mdia_t *mdia);
longest quicktime_position(quicktime_t *file);
int quicktime_read_minf(quicktime_t *file,quicktime_minf_t *minf,quicktime_atom_t *parent_atom);
int quicktime_atom_skip(quicktime_t *file,quicktime_atom_t *atom);
void quicktime_read_hdlr(quicktime_t *file,quicktime_hdlr_t *hdlr);
void quicktime_read_mdhd(quicktime_t *file,quicktime_mdhd_t *mdhd);
int quicktime_atom_is(quicktime_atom_t *atom,char *type);
int quicktime_atom_read_header(quicktime_t *file,quicktime_atom_t *atom);
int quicktime_read_mdia(quicktime_t *file,quicktime_mdia_t *mdia,quicktime_atom_t *trak_atom);
void quicktime_minf_dump(quicktime_minf_t *minf);
void quicktime_hdlr_dump(quicktime_hdlr_t *hdlr);
void quicktime_mdhd_dump(quicktime_mdhd_t *mdhd);
void quicktime_mdia_dump(quicktime_mdia_t *mdia);
void quicktime_minf_delete(quicktime_minf_t *minf);
void quicktime_hdlr_delete(quicktime_hdlr_t *hdlr);
void quicktime_mdhd_delete(quicktime_mdhd_t *mdhd);
void quicktime_mdia_delete(quicktime_mdia_t *mdia);
void quicktime_hdlr_init_audio(quicktime_hdlr_t *hdlr);
void quicktime_minf_init_audio(quicktime_t *file,quicktime_minf_t *minf,int channels,int sample_rate,int bits,char *compressor);
void quicktime_mdhd_init_audio(quicktime_t *file,quicktime_mdhd_t *mdhd,int channels,int sample_rate,int bits,char *compressor);
void quicktime_mdia_init_audio(quicktime_t *file,quicktime_mdia_t *mdia,int channels,int sample_rate,int bits,char *compressor);
void quicktime_hdlr_init_video(quicktime_hdlr_t *hdlr);
void quicktime_minf_init_video(quicktime_t *file,quicktime_minf_t *minf,int frame_w,int frame_h,int time_scale,float frame_rate,char *compressor);
void quicktime_mdhd_init_video(quicktime_t *file,quicktime_mdhd_t *mdhd,int frame_w,int frame_h,float frame_rate);
void quicktime_mdia_init_video(quicktime_t *file,quicktime_mdia_t *mdia,int frame_w,int frame_h,float frame_rate,char *compressor);
void quicktime_minf_init(quicktime_minf_t *minf);
void quicktime_hdlr_init(quicktime_hdlr_t *hdlr);
void quicktime_mdhd_init(quicktime_mdhd_t *mdhd);
void quicktime_mdia_init(quicktime_mdia_t *mdia);
