/* This file was automatically generated.  Do not edit! */
int quicktime_trak_shift_offsets(quicktime_trak_t *trak,longest offset);
int quicktime_shift_offsets(quicktime_moov_t *moov,longest offset);
void quicktime_update_durations(quicktime_moov_t *moov);
void quicktime_atom_write_footer(quicktime_t *file,quicktime_atom_t *atom);
int quicktime_write_trak(quicktime_t *file,quicktime_trak_t *trak,long moov_time_scale);
void quicktime_write_udta(quicktime_t *file,quicktime_udta_t *udta);
void quicktime_write_mvhd(quicktime_t *file,quicktime_mvhd_t *mvhd);
int quicktime_trak_duration(quicktime_trak_t *trak,long *duration,long *timescale);
int quicktime_trak_fix_counts(quicktime_t *file,quicktime_trak_t *trak);
int quicktime_set_position(quicktime_t *file,longest position);
int quicktime_atom_write_header(quicktime_t *file,quicktime_atom_t *atom,char *text);
void quicktime_write_moov(quicktime_t *file,quicktime_moov_t *moov);
longest quicktime_position(quicktime_t *file);
int quicktime_read_ctab(quicktime_t *file,quicktime_ctab_t *ctab);
int quicktime_read_udta(quicktime_t *file,quicktime_udta_t *udta,quicktime_atom_t *udta_atom);
int quicktime_read_trak(quicktime_t *file,quicktime_trak_t *trak,quicktime_atom_t *trak_atom);
quicktime_trak_t *quicktime_add_trak(quicktime_moov_t *moov);
int quicktime_atom_skip(quicktime_t *file,quicktime_atom_t *atom);
void quicktime_read_mvhd(quicktime_t *file,quicktime_mvhd_t *mvhd);
int quicktime_atom_is(quicktime_atom_t *atom,char *type);
int quicktime_atom_read_header(quicktime_t *file,quicktime_atom_t *atom);
int quicktime_read_moov(quicktime_t *file,quicktime_moov_t *moov,quicktime_atom_t *parent_atom);
void quicktime_ctab_dump(quicktime_ctab_t *ctab);
int quicktime_trak_dump(quicktime_trak_t *trak);
void quicktime_udta_dump(quicktime_udta_t *udta);
void quicktime_mvhd_dump(quicktime_mvhd_t *mvhd);
void quicktime_moov_dump(quicktime_moov_t *moov);
int quicktime_ctab_delete(quicktime_ctab_t *ctab);
int quicktime_udta_delete(quicktime_udta_t *udta);
int quicktime_mvhd_delete(quicktime_mvhd_t *mvhd);
int quicktime_delete_trak(quicktime_moov_t *moov);
int quicktime_moov_delete(quicktime_moov_t *moov);
int quicktime_ctab_init(quicktime_ctab_t *ctab);
int quicktime_udta_init(quicktime_udta_t *udta);
int quicktime_mvhd_init(quicktime_mvhd_t *mvhd);
int quicktime_moov_init(quicktime_moov_t *moov);
