/* This file was automatically generated.  Do not edit! */
void quicktime_atom_write_footer(quicktime_t *file,quicktime_atom_t *atom);
void quicktime_write_matrix(quicktime_t *file,quicktime_matrix_t *matrix);
int quicktime_write_data(quicktime_t *file,char *data,int size);
int quicktime_write_fixed16(quicktime_t *file,float number);
int quicktime_write_fixed32(quicktime_t *file,float number);
int quicktime_write_int32(quicktime_t *file,long value);
int quicktime_write_int24(quicktime_t *file,long number);
int quicktime_write_char(quicktime_t *file,char x);
int quicktime_atom_write_header(quicktime_t *file,quicktime_atom_t *atom,char *text);
void quicktime_write_mvhd(quicktime_t *file,quicktime_mvhd_t *mvhd);
int quicktime_get_timescale(float frame_rate);
int quicktime_get_timescale(float frame_rate);
void quicktime_mhvd_init_video(quicktime_t *file,quicktime_mvhd_t *mvhd,float frame_rate);
void quicktime_read_matrix(quicktime_t *file,quicktime_matrix_t *matrix);
int quicktime_read_data(quicktime_t *file,char *data,longest size);
float quicktime_read_fixed16(quicktime_t *file);
float quicktime_read_fixed32(quicktime_t *file);
long quicktime_read_int32(quicktime_t *file);
long quicktime_read_int24(quicktime_t *file);
int quicktime_read_char(quicktime_t *file);
void quicktime_read_mvhd(quicktime_t *file,quicktime_mvhd_t *mvhd);
void quicktime_matrix_dump(quicktime_matrix_t *matrix);
void quicktime_print_chars(char *desc,char *input,int len);
void quicktime_mvhd_dump(quicktime_mvhd_t *mvhd);
int quicktime_mvhd_delete(quicktime_mvhd_t *mvhd);
void quicktime_matrix_init(quicktime_matrix_t *matrix);
unsigned long quicktime_current_time(void);
int quicktime_mvhd_init(quicktime_mvhd_t *mvhd);
