/* This file was automatically generated.  Do not edit! */
void quicktime_atom_write_footer(quicktime_t *file,quicktime_atom_t *atom);
int quicktime_codecs_flush(quicktime_t *file);
int quicktime_codecs_flush(quicktime_t *file);
int quicktime_atom_write_header64(quicktime_t *file,quicktime_atom_t *atom,char *text);
int quicktime_check_sig(char *path);
int quicktime_check_sig(char *path);
void quicktime_moov_dump(quicktime_moov_t *moov);
int quicktime_dump(quicktime_t *file);
int quicktime_dump(quicktime_t *file);
int quicktime_read_moov(quicktime_t *file,quicktime_moov_t *moov,quicktime_atom_t *parent_atom);
void quicktime_read_mdat(quicktime_t *file,quicktime_mdat_t *mdat,quicktime_atom_t *parent_atom);
void quicktime_read_char32(quicktime_t *file,char *string);
int quicktime_read_info(quicktime_t *file);
int quicktime_read_info(quicktime_t *file);
int quicktime_delete_acodec(quicktime_audio_map_t *atrack);
int quicktime_delete_acodec(quicktime_audio_map_t *atrack);
int quicktime_init_acodec(quicktime_audio_map_t *atrack);
int quicktime_init_acodec(quicktime_audio_map_t *atrack,int encode);
int quicktime_delete_vcodec(quicktime_video_map_t *vtrack);
int quicktime_delete_vcodec(quicktime_video_map_t *vtrack);
int quicktime_init_vcodec(quicktime_video_map_t *vtrack);
int quicktime_init_vcodec(quicktime_video_map_t *vtrack,int encode);
int quicktime_read_frame_end(quicktime_t *file,int track);
int quicktime_read_frame_end(quicktime_t *file,int track);
int64_t quicktime_ftell(quicktime_t *file);
int quicktime_read_frame_init(quicktime_t *file,int track);
int quicktime_read_frame_init(quicktime_t *file,int track);
int quicktime_has_keyframes(quicktime_t *file,int track);
int quicktime_has_keyframes(quicktime_t *file,int track);
void quicktime_insert_keyframe(quicktime_t *file,long frame,int track);
void quicktime_insert_keyframe(quicktime_t *file,long frame,int track);
long quicktime_get_keyframe_before(quicktime_t *file,long frame,int track);
long quicktime_get_keyframe_before(quicktime_t *file,long frame,int track);
long quicktime_read_frame(quicktime_t *file,unsigned char *video_buffer,int track);
long quicktime_read_frame(quicktime_t *file,unsigned char *video_buffer,int track);
long quicktime_frame_size(quicktime_t *file,long frame,int track);
long quicktime_frame_size(quicktime_t *file,long frame,int track);
int64_t quicktime_chunk_to_offset(quicktime_trak_t *trak,long chunk);
int quicktime_read_chunk(quicktime_t *file,char *output,int track,int64_t chunk,int64_t byte_start,int64_t byte_len);
int quicktime_read_chunk(quicktime_t *file,char *output,int track,int64_t chunk,int64_t byte_start,int64_t byte_len);
int64_t quicktime_samples_to_bytes(quicktime_trak_t *track,long samples);
int64_t quicktime_samples_to_bytes(quicktime_trak_t *track,long samples);
long quicktime_chunk_samples(quicktime_trak_t *trak,long chunk);
long quicktime_read_audio(quicktime_t *file,char *audio_buffer,long samples,int track);
long quicktime_read_audio(quicktime_t *file,char *audio_buffer,long samples,int track);
int quicktime_write_frame(quicktime_t *file,unsigned char *video_buffer,int64_t bytes,int track);
int quicktime_write_frame(quicktime_t *file,unsigned char *video_buffer,int64_t bytes,int track);
int quicktime_update_tables(quicktime_t *file,quicktime_trak_t *trak,int64_t offset,int64_t chunk,int64_t sample,int64_t samples,int64_t sample_size);
int quicktime_write_audio(quicktime_t *file,char *audio_buffer,long samples,int track);
int quicktime_write_audio(quicktime_t *file,char *audio_buffer,long samples,int track);
char *quicktime_video_compressor(quicktime_t *file,int track);
char *quicktime_video_compressor(quicktime_t *file,int track);
float quicktime_frame_rate(quicktime_t *file,int track);
float quicktime_frame_rate(quicktime_t *file,int track);
void quicktime_set_depth(quicktime_t *file,int depth,int track);
void quicktime_set_depth(quicktime_t *file,int depth,int track);
void quicktime_set_row_span(quicktime_t *file,int row_span);
void quicktime_set_row_span(quicktime_t *file,int row_span);
void quicktime_set_cmodel(quicktime_t *file,int colormodel);
void quicktime_set_cmodel(quicktime_t *file,int colormodel);
int quicktime_video_depth(quicktime_t *file,int track);
int quicktime_video_depth(quicktime_t *file,int track);
int quicktime_video_height(quicktime_t *file,int track);
int quicktime_video_height(quicktime_t *file,int track);
int quicktime_video_width(quicktime_t *file,int track);
int quicktime_video_width(quicktime_t *file,int track);
int quicktime_has_video(quicktime_t *file);
int quicktime_has_video(quicktime_t *file);
int quicktime_channel_location(quicktime_t *file,int *quicktime_track,int *quicktime_channel,int channel);
int quicktime_channel_location(quicktime_t *file,int *quicktime_track,int *quicktime_channel,int channel);
int quicktime_track_channels(quicktime_t *file,int track);
int quicktime_track_channels(quicktime_t *file,int track);
char *quicktime_audio_compressor(quicktime_t *file,int track);
char *quicktime_audio_compressor(quicktime_t *file,int track);
int quicktime_audio_bits(quicktime_t *file,int track);
int quicktime_audio_bits(quicktime_t *file,int track);
long quicktime_sample_rate(quicktime_t *file,int track);
long quicktime_sample_rate(quicktime_t *file,int track);
int quicktime_has_audio(quicktime_t *file);
int quicktime_has_audio(quicktime_t *file);
int quicktime_set_video_position(quicktime_t *file,int64_t frame,int track);
int quicktime_set_video_position(quicktime_t *file,int64_t frame,int track);
int64_t quicktime_sample_to_offset(quicktime_trak_t *trak,long sample);
int quicktime_chunk_of_sample(int64_t *chunk_sample,int64_t *chunk,quicktime_trak_t *trak,long sample);
int quicktime_set_audio_position(quicktime_t *file,int64_t sample,int track);
int quicktime_set_audio_position(quicktime_t *file,int64_t sample,int track);
long quicktime_offset_to_chunk(int64_t *chunk_offset,quicktime_trak_t *trak,int64_t offset);
long quicktime_offset_to_sample(quicktime_trak_t *trak,int64_t offset);
long quicktime_video_position(quicktime_t *file,int track);
long quicktime_video_position(quicktime_t *file,int track);
long quicktime_audio_position(quicktime_t *file,int track);
long quicktime_audio_position(quicktime_t *file,int track);
long quicktime_video_length(quicktime_t *file,int track);
long quicktime_video_length(quicktime_t *file,int track);
long quicktime_track_samples(quicktime_t *file,quicktime_trak_t *trak);
long quicktime_audio_length(quicktime_t *file,int track);
long quicktime_audio_length(quicktime_t *file,int track);
int quicktime_seek_start(quicktime_t *file);
int quicktime_seek_start(quicktime_t *file);
int quicktime_update_positions(quicktime_t *file);
int quicktime_update_positions(quicktime_t *file);
int quicktime_seek_end(quicktime_t *file);
int quicktime_seek_end(quicktime_t *file);
void quicktime_set_preload(quicktime_t *file,int64_t preload);
void quicktime_set_preload(quicktime_t *file,int64_t preload);
int quicktime_set_cpus(quicktime_t *file,int cpus);
int quicktime_set_cpus(quicktime_t *file,int cpus);
void quicktime_mdat_delete(quicktime_mdat_t *mdat);
int quicktime_moov_delete(quicktime_moov_t *moov);
int quicktime_delete_video_map(quicktime_video_map_t *vtrack);
int quicktime_delete_video_map(quicktime_video_map_t *vtrack);
int quicktime_delete_audio_map(quicktime_audio_map_t *atrack);
int quicktime_delete_audio_map(quicktime_audio_map_t *atrack);
int quicktime_delete(quicktime_t *file);
int quicktime_delete(quicktime_t *file);
int quicktime_moov_init(quicktime_moov_t *moov);
int quicktime_trak_init(quicktime_trak_t *trak);
int quicktime_get_timescale(float frame_rate);
int quicktime_get_timescale(float frame_rate);
void quicktime_set_framerate(quicktime_t *file,float framerate);
void quicktime_set_framerate(quicktime_t *file,float framerate);
int quicktime_init_video_map(quicktime_video_map_t *vtrack,quicktime_trak_t *trak,int encode);
int quicktime_init_video_map(quicktime_video_map_t *vtrack,quicktime_trak_t *trak);
int quicktime_trak_init_video(quicktime_t *file,quicktime_trak_t *trak,int frame_w,int frame_h,float frame_rate,char *compressor);
void quicktime_mhvd_init_video(quicktime_t *file,quicktime_mvhd_t *mvhd,float frame_rate);
int quicktime_set_video(quicktime_t *file,int tracks,int frame_w,int frame_h,float frame_rate,char *compressor);
int quicktime_set_video(quicktime_t *file,int tracks,int frame_w,int frame_h,float frame_rate,char *compressor);
int quicktime_init_audio_map(quicktime_audio_map_t *atrack,quicktime_trak_t *trak,int encode);
int quicktime_init_audio_map(quicktime_audio_map_t *atrack,quicktime_trak_t *trak);
int quicktime_trak_init_audio(quicktime_t *file,quicktime_trak_t *trak,int channels,int sample_rate,int bits,char *compressor);
quicktime_trak_t *quicktime_add_track(quicktime_moov_t *moov);
quicktime_trak_t *quicktime_add_track(quicktime_moov_t *moov);
int quicktime_match_32(char *input,char *output);
int quicktime_set_audio(quicktime_t *file,int channels,long sample_rate,int bits,char *compressor);
int quicktime_set_audio(quicktime_t *file,int channels,long sample_rate,int bits,char *compressor);
int quicktime_audio_tracks(quicktime_t *file);
int quicktime_audio_tracks(quicktime_t *file);
int quicktime_video_tracks(quicktime_t *file);
int quicktime_video_tracks(quicktime_t *file);
char *quicktime_get_info(quicktime_t *file);
char *quicktime_get_info(quicktime_t *file);
char *quicktime_get_name(quicktime_t *file);
char *quicktime_get_name(quicktime_t *file);
char *quicktime_get_copyright(quicktime_t *file);
char *quicktime_get_copyright(quicktime_t *file);
void quicktime_set_info(quicktime_t *file,char *string);
void quicktime_set_info(quicktime_t *file,char *string);
void quicktime_set_name(quicktime_t *file,char *string);
void quicktime_set_name(quicktime_t *file,char *string);
int quicktime_set_udta_string(char **string,int *size,char *new_string);
void quicktime_set_copyright(quicktime_t *file,char *string);
void quicktime_set_copyright(quicktime_t *file,char *string);
void quicktime_set_parameter(quicktime_t *file,char *key,void *value);
void quicktime_set_parameter(quicktime_t *file,char *key,void *value);
int quicktime_close(quicktime_t *file);
int quicktime_close(quicktime_t *file);
int quicktime_write_data(quicktime_t *file,char *data,int size);
int quicktime_read_data(quicktime_t *file,char *data,int64_t size);
int quicktime_set_position(quicktime_t *file,int64_t position);
void quicktime_write_moov(quicktime_t *file,quicktime_moov_t *moov);
int quicktime_shift_offsets(quicktime_moov_t *moov,int64_t offset);
quicktime_t *quicktime_open(char *filename,int rd,int wr);
quicktime_t *quicktime_open(char *filename,int rd,int wr);
int quicktime_atom_skip(quicktime_t *file,quicktime_atom_t *atom);
int64_t quicktime_position(quicktime_t *file);
int quicktime_atom_is(quicktime_atom_t *atom,char *type);
int quicktime_atom_read_header(quicktime_t *file,quicktime_atom_t *atom);
int quicktime_init(quicktime_t *file);
int quicktime_init(quicktime_t *file);
int quicktime_make_streamable(char *in_path,char *out_path);
int quicktime_make_streamable(char *in_path,char *out_path);
