/* This file was automatically generated.  Do not edit! */
void quicktime_atom_write_footer(quicktime_t *file,quicktime_atom_t *atom);
void quicktime_write_stco(quicktime_t *file,quicktime_stco_t *stco);
void quicktime_write_stsz(quicktime_t *file,quicktime_stsz_t *stsz);
void quicktime_write_stsc(quicktime_t *file,quicktime_stsc_t *stsc);
void quicktime_write_stss(quicktime_t *file,quicktime_stss_t *stss);
void quicktime_write_stts(quicktime_t *file,quicktime_stts_t *stts);
void quicktime_write_stsd(quicktime_t *file,quicktime_minf_t *minf,quicktime_stsd_t *stsd);
int quicktime_atom_write_header(quicktime_t *file,quicktime_atom_t *atom,char *text);
void quicktime_write_stbl(quicktime_t *file,quicktime_minf_t *minf,quicktime_stbl_t *stbl);
longest quicktime_position(quicktime_t *file);
void quicktime_read_stco(quicktime_t *file,quicktime_stco_t *stco);
void quicktime_read_stco64(quicktime_t *file,quicktime_stco_t *stco);
void quicktime_read_stsz(quicktime_t *file,quicktime_stsz_t *stsz);
void quicktime_read_stsc(quicktime_t *file,quicktime_stsc_t *stsc);
void quicktime_read_stss(quicktime_t *file,quicktime_stss_t *stss);
void quicktime_read_stts(quicktime_t *file,quicktime_stts_t *stts);
int quicktime_atom_skip(quicktime_t *file,quicktime_atom_t *atom);
void quicktime_read_stsd(quicktime_t *file,quicktime_minf_t *minf,quicktime_stsd_t *stsd);
int quicktime_atom_is(quicktime_atom_t *atom,char *type);
int quicktime_atom_read_header(quicktime_t *file,quicktime_atom_t *atom);
int quicktime_read_stbl(quicktime_t *file,quicktime_minf_t *minf,quicktime_stbl_t *stbl,quicktime_atom_t *parent_atom);
void quicktime_stco_dump(quicktime_stco_t *stco);
void quicktime_stsz_dump(quicktime_stsz_t *stsz);
void quicktime_stsc_dump(quicktime_stsc_t *stsc);
void quicktime_stss_dump(quicktime_stss_t *stss);
void quicktime_stts_dump(quicktime_stts_t *stts);
void quicktime_stsd_dump(void *minf_ptr,quicktime_stsd_t *stsd);
void quicktime_stbl_dump(void *minf_ptr,quicktime_stbl_t *stbl);
void quicktime_stco_delete(quicktime_stco_t *stco);
void quicktime_stsz_delete(quicktime_stsz_t *stsz);
void quicktime_stsc_delete(quicktime_stsc_t *stsc);
void quicktime_stss_delete(quicktime_stss_t *stss);
void quicktime_stts_delete(quicktime_stts_t *stts);
void quicktime_stsd_delete(quicktime_stsd_t *stsd);
void quicktime_stbl_delete(quicktime_stbl_t *stbl);
void quicktime_stsz_init_audio(quicktime_t *file,quicktime_stsz_t *stsz,int channels,int bits,char *compressor);
void quicktime_stsc_init_audio(quicktime_t *file,quicktime_stsc_t *stsc,int sample_rate);
void quicktime_stts_init_audio(quicktime_t *file,quicktime_stts_t *stts,int sample_rate);
void quicktime_stsd_init_audio(quicktime_t *file,quicktime_stsd_t *stsd,int channels,int sample_rate,int bits,char *compressor);
void quicktime_stbl_init_audio(quicktime_t *file,quicktime_stbl_t *stbl,int channels,int sample_rate,int bits,char *compressor);
void quicktime_stco_init_common(quicktime_t *file,quicktime_stco_t *stco);
void quicktime_stsz_init_video(quicktime_t *file,quicktime_stsz_t *stsz);
void quicktime_stsc_init_video(quicktime_t *file,quicktime_stsc_t *stsc);
void quicktime_stts_init_video(quicktime_t *file,quicktime_stts_t *stts,int time_scale,float frame_rate);
void quicktime_stsd_init_video(quicktime_t *file,quicktime_stsd_t *stsd,int frame_w,int frame_h,float frame_rate,char *compression);
void quicktime_stbl_init_video(quicktime_t *file,quicktime_stbl_t *stbl,int frame_w,int frame_h,int time_scale,float frame_rate,char *compressor);
void quicktime_stco_init(quicktime_stco_t *stco);
void quicktime_stsz_init(quicktime_stsz_t *stsz);
void quicktime_stsc_init(quicktime_stsc_t *stsc);
void quicktime_stss_init(quicktime_stss_t *stss);
void quicktime_stts_init(quicktime_stts_t *stts);
void quicktime_stsd_init(quicktime_stsd_t *stsd);
void quicktime_stbl_init(quicktime_stbl_t *stbl);
