/* This file was automatically generated.  Do not edit! */
void quicktime_update_stco(quicktime_stco_t *stco,long chunk,longest offset);
void quicktime_atom_write_footer(quicktime_t *file,quicktime_atom_t *atom);
int quicktime_write_int64(quicktime_t *file,longest value);
int quicktime_write_int32(quicktime_t *file,long value);
int quicktime_write_int24(quicktime_t *file,long number);
int quicktime_write_char(quicktime_t *file,char x);
int quicktime_atom_write_header(quicktime_t *file,quicktime_atom_t *atom,char *text);
void quicktime_write_stco(quicktime_t *file,quicktime_stco_t *stco);
longest quicktime_read_int64(quicktime_t *file);
void quicktime_read_stco64(quicktime_t *file,quicktime_stco_t *stco);
unsigned long quicktime_read_uint32(quicktime_t *file);
long quicktime_read_int32(quicktime_t *file);
long quicktime_read_int24(quicktime_t *file);
int quicktime_read_char(quicktime_t *file);
void quicktime_read_stco(quicktime_t *file,quicktime_stco_t *stco);
void quicktime_stco_dump(quicktime_stco_t *stco);
void quicktime_stco_init_common(quicktime_t *file,quicktime_stco_t *stco);
void quicktime_stco_delete(quicktime_stco_t *stco);
void quicktime_stco_init(quicktime_stco_t *stco);
