/* This file was automatically generated.  Do not edit! */
void quicktime_atom_write_footer(quicktime_t *file,quicktime_atom_t *atom);
void quicktime_write_stsd_table(quicktime_t *file,quicktime_minf_t *minf,quicktime_stsd_table_t *table);
int quicktime_write_int32(quicktime_t *file,long value);
int quicktime_write_int24(quicktime_t *file,long number);
int quicktime_write_char(quicktime_t *file,char x);
int quicktime_atom_write_header(quicktime_t *file,quicktime_atom_t *atom,char *text);
void quicktime_write_stsd(quicktime_t *file,quicktime_minf_t *minf,quicktime_stsd_t *stsd);
void quicktime_read_stsd_table(quicktime_t *file,quicktime_minf_t *minf,quicktime_stsd_table_t *table);
long quicktime_read_int32(quicktime_t *file);
long quicktime_read_int24(quicktime_t *file);
int quicktime_read_char(quicktime_t *file);
void quicktime_read_stsd(quicktime_t *file,quicktime_minf_t *minf,quicktime_stsd_t *stsd);
void quicktime_stsd_table_dump(void *minf_ptr,quicktime_stsd_table_t *table);
void quicktime_stsd_dump(void *minf_ptr,quicktime_stsd_t *stsd);
void quicktime_stsd_table_delete(quicktime_stsd_table_t *table);
void quicktime_stsd_delete(quicktime_stsd_t *stsd);
void quicktime_stsd_init_audio(quicktime_t *file,quicktime_stsd_t *stsd,int channels,int sample_rate,int bits,char *compressor);
void quicktime_copy_char32(char *output,char *input);
void quicktime_stsd_init_video(quicktime_t *file,quicktime_stsd_t *stsd,int frame_w,int frame_h,float frame_rate,char *compression);
void quicktime_stsd_table_init(quicktime_stsd_table_t *table);
void quicktime_stsd_init_table(quicktime_stsd_t *stsd);
void quicktime_stsd_init(quicktime_stsd_t *stsd);
