/* This file was automatically generated.  Do not edit! */
void quicktime_tkhd_init_video(quicktime_t *file,quicktime_tkhd_t *tkhd,int frame_w,int frame_h);
void quicktime_atom_write_footer(quicktime_t *file,quicktime_atom_t *atom);
int quicktime_write_fixed32(quicktime_t *file,float number);
void quicktime_write_matrix(quicktime_t *file,quicktime_matrix_t *matrix);
int quicktime_write_fixed16(quicktime_t *file,float number);
int quicktime_write_int16(quicktime_t *file,int number);
int quicktime_write_data(quicktime_t *file,char *data,int size);
int quicktime_write_int32(quicktime_t *file,long value);
int quicktime_write_int24(quicktime_t *file,long number);
int quicktime_write_char(quicktime_t *file,char x);
int quicktime_atom_write_header(quicktime_t *file,quicktime_atom_t *atom,char *text);
void quicktime_write_tkhd(quicktime_t *file,quicktime_tkhd_t *tkhd);
float quicktime_read_fixed32(quicktime_t *file);
void quicktime_read_matrix(quicktime_t *file,quicktime_matrix_t *matrix);
float quicktime_read_fixed16(quicktime_t *file);
int quicktime_read_int16(quicktime_t *file);
int quicktime_read_data(quicktime_t *file,char *data,longest size);
long quicktime_read_int32(quicktime_t *file);
long quicktime_read_int24(quicktime_t *file);
int quicktime_read_char(quicktime_t *file);
void quicktime_read_tkhd(quicktime_t *file,quicktime_tkhd_t *tkhd);
void quicktime_matrix_dump(quicktime_matrix_t *matrix);
void quicktime_print_chars(char *desc,char *input,int len);
void quicktime_tkhd_dump(quicktime_tkhd_t *tkhd);
int quicktime_tkhd_delete(quicktime_tkhd_t *tkhd);
void quicktime_matrix_init(quicktime_matrix_t *matrix);
unsigned long quicktime_current_time(void);
int quicktime_tkhd_init(quicktime_tkhd_t *tkhd);
