/* This file was automatically generated.  Do not edit! */
int quicktime_trak_shift_offsets(quicktime_trak_t *trak,longest offset);
long quicktime_chunk_samples(quicktime_trak_t *trak,long chunk);
int quicktime_trak_fix_counts(quicktime_t *file,quicktime_trak_t *trak);
int quicktime_update_stsc(quicktime_stsc_t *stsc,long chunk,long samples);
void quicktime_update_stsz(quicktime_stsz_t *stsz,long sample,long sample_size);
void quicktime_update_stco(quicktime_stco_t *stco,long chunk,longest offset);
int quicktime_update_tables(quicktime_t *file,quicktime_trak_t *trak,longest offset,longest chunk,longest sample,longest samples,longest sample_size);
long quicktime_offset_to_sample(quicktime_trak_t *trak,longest offset);
longest quicktime_sample_to_offset(quicktime_trak_t *trak,long sample);
longest quicktime_samples_to_bytes(quicktime_trak_t *track,long samples);
longest quicktime_samples_to_bytes(quicktime_trak_t *track,long samples);
longest quicktime_sample_range_size(quicktime_trak_t *trak,long chunk_sample,long sample);
long quicktime_offset_to_chunk(longest *chunk_offset,quicktime_trak_t *trak,longest offset);
longest quicktime_chunk_to_offset(quicktime_trak_t *trak,long chunk);
int quicktime_chunk_of_sample(longest *chunk_sample,longest *chunk,quicktime_trak_t *trak,long sample);
long quicktime_sample_of_chunk(quicktime_trak_t *trak,long chunk);
long quicktime_track_samples(quicktime_t *file,quicktime_trak_t *trak);
longest quicktime_track_end(quicktime_trak_t *trak);
void quicktime_atom_write_footer(quicktime_t *file,quicktime_atom_t *atom);
void quicktime_write_mdia(quicktime_t *file,quicktime_mdia_t *mdia);
void quicktime_write_edts(quicktime_t *file,quicktime_edts_t *edts,long duration);
void quicktime_write_tkhd(quicktime_t *file,quicktime_tkhd_t *tkhd);
int quicktime_trak_duration(quicktime_trak_t *trak,long *duration,long *timescale);
int quicktime_atom_write_header(quicktime_t *file,quicktime_atom_t *atom,char *text);
int quicktime_write_trak(quicktime_t *file,quicktime_trak_t *trak,long moov_time_scale);
longest quicktime_position(quicktime_t *file);
void quicktime_read_edts(quicktime_t *file,quicktime_edts_t *edts,quicktime_atom_t *edts_atom);
int quicktime_atom_skip(quicktime_t *file,quicktime_atom_t *atom);
int quicktime_read_mdia(quicktime_t *file,quicktime_mdia_t *mdia,quicktime_atom_t *trak_atom);
void quicktime_read_tkhd(quicktime_t *file,quicktime_tkhd_t *tkhd);
int quicktime_atom_is(quicktime_atom_t *atom,char *type);
int quicktime_atom_read_header(quicktime_t *file,quicktime_atom_t *atom);
int quicktime_read_trak(quicktime_t *file,quicktime_trak_t *trak,quicktime_atom_t *trak_atom);
int quicktime_delete_trak(quicktime_moov_t *moov);
quicktime_trak_t *quicktime_add_trak(quicktime_moov_t *moov);
void quicktime_mdia_dump(quicktime_mdia_t *mdia);
void quicktime_edts_dump(quicktime_edts_t *edts);
void quicktime_tkhd_dump(quicktime_tkhd_t *tkhd);
int quicktime_trak_dump(quicktime_trak_t *trak);
int quicktime_tkhd_delete(quicktime_tkhd_t *tkhd);
int quicktime_trak_delete(quicktime_trak_t *trak);
void quicktime_mdia_init_audio(quicktime_t *file,quicktime_mdia_t *mdia,int channels,int sample_rate,int bits,char *compressor);
int quicktime_trak_init_audio(quicktime_t *file,quicktime_trak_t *trak,int channels,int sample_rate,int bits,char *compressor);
void quicktime_edts_init_table(quicktime_edts_t *edts);
void quicktime_mdia_init_video(quicktime_t *file,quicktime_mdia_t *mdia,int frame_w,int frame_h,float frame_rate,char *compressor);
void quicktime_tkhd_init_video(quicktime_t *file,quicktime_tkhd_t *tkhd,int frame_w,int frame_h);
int quicktime_trak_init_video(quicktime_t *file,quicktime_trak_t *trak,int frame_w,int frame_h,float frame_rate,char *compressor);
void quicktime_mdia_init(quicktime_mdia_t *mdia);
void quicktime_edts_init(quicktime_edts_t *edts);
int quicktime_tkhd_init(quicktime_tkhd_t *tkhd);
int quicktime_trak_init(quicktime_trak_t *trak);
