/* This file was automatically generated.  Do not edit! */
int quicktime_match_32(char *input,char *output);
unsigned long quicktime_current_time(void);
void quicktime_print_chars(char *desc,char *input,int len);
void quicktime_copy_char32(char *output,char *input);
int quicktime_set_position(quicktime_t *file,int64_t position);
void quicktime_read_char32(quicktime_t *file,char *string);
int quicktime_write_char(quicktime_t *file,char x);
int quicktime_write_int16(quicktime_t *file,int number);
int quicktime_read_int16(quicktime_t *file);
int quicktime_write_int24(quicktime_t *file,long number);
long quicktime_read_int24(quicktime_t *file);
int64_t quicktime_read_int64(quicktime_t *file);
long quicktime_read_int32(quicktime_t *file);
unsigned long quicktime_read_uint32(quicktime_t *file);
int quicktime_write_fixed16(quicktime_t *file,float number);
float quicktime_read_fixed16(quicktime_t *file);
int quicktime_write_char32(quicktime_t *file,char *string);
int quicktime_write_int32(quicktime_t *file,long value);
int quicktime_write_int64(quicktime_t *file,int64_t value);
int quicktime_write_fixed32(quicktime_t *file,float number);
float quicktime_read_fixed32(quicktime_t *file);
void quicktime_write_pascal(quicktime_t *file,char *data);
int quicktime_read_char(quicktime_t *file);
void quicktime_read_pascal(quicktime_t *file,char *data);
int64_t quicktime_position(quicktime_t *file);
int64_t quicktime_byte_position(quicktime_t *file);
int quicktime_write_data(quicktime_t *file,char *data,int size);
int quicktime_read_data(quicktime_t *file,char *data,int64_t size);
int64_t quicktime_add(int64_t a,int64_t b);
int quicktime_fseek(quicktime_t *file,int64_t offset);
int64_t quicktime_ftell(quicktime_t *file);
